// Image (image) — Mysterious Roman Dodecahedron by sylvain69780
// https://www.shadertoy.com/view/Nsd3Wl

/*
 
    Mysterious Roman dodecahedron
    -----------------------------
    
    While visiting the Lugdunum Museum at Lyon (France) I was shocked by a very strange artifact ! 
    
    A Roman dodecahedron or Gallo-Roman dodecahedron is a small hollow object 
    made of copper alloy which has been cast into a regular dodecahedral shape: 
    twelve flat pentagonal faces, each face having a circular hole of varying 
    diameter in the middle, the holes connecting to the hollow center. 
    Roman dodecahedra date from the 2nd to 4th centuries AD.    

    Some people suggested it is a simple tool to make gloves because they are found 
    only on the north of Europe, I prefer to think it's a kind of magic object. 
    We will probably never know !
    
    It's amazing what people were able to do even before Shadertoy was created.

    Related references:
    
    Roman dodecahedron - Wikipedia
    https://en.wikipedia.org/wiki/Roman_dodecahedron

    Wythoff explorer - mattz ♥ 
    https://www.shadertoy.com/view/Md3yRB

    icosahedronal symmetry & Icosahedron Weave - DjinnKahn
    https://www.shadertoy.com/view/Mly3R3
    https://www.shadertoy.com/view/Xty3Dy

    Polyhedron again - knighty
    https://www.shadertoy.com/view/XlX3zB

    Polyhedrons, many many polyhedrons... - Fractalforums
    https://www.fractalforums.com/fragmentarium/solids-many-many-solids/30/
        
    Wythoff Mathematical Details - Greg Egan
    http://www.gregegan.net/APPLETS/26/WythoffNotes.html
        
    heavy metal squiggle orb - mattz
    https://www.shadertoy.com/view/wsGfD3

    IQ Distance functions
    https://iquilezles.org/articles/distfunctions

    Wythoff Polyhedra with Exact SDF - mla
    https://www.shadertoy.com/view/WlccR8

    The so-called "folding" technique consists in using a succession of reflections 
    to end up with a reduced domain of coordinates 
       
    The **spherical** triangle used to fold the coordinates is (P, Q, R) with **fractions of PI** PI/2, PI/3 , PI/5 for angles. 
    Even if the drawing below is FLAT, it represents a triangle on a SPHERE.
    
      Q=3 *--__
          |    ^^--__
      R=2 *----------* P = 5
    
    The sum of these angles is more than PI (180°), this is because we are tiling a sphere here.
    
    The shape generated by the distance field using the z direction 
    is a Rhombic Triacontahedron made of 30 rhombic faces formed by 4 coplanar triangles.

    Icosahedron and Dodecahedrons : you get it by rotation of the plan of this triangle around the X or Y axis.
    R is the middle of an edge of the Ico or Dode
    Q is the vertex of a Dode, middle of the face of an Ico
    P is the vertex of an Ico, middle of the face of a Dode
    
*/

// folding function - here only 3 fold loops 
// https://www.shadertoy.com/view/ltlGWM
// https://en.wikipedia.org/wiki/Polyhedral_group
vec3 opIcosahedralSymmetry( vec3 p )
{    
    // const float c = cos(PI/5.), s=sqrt(0.75-c*c);
    // cos(PI/5.) = 0.80901699437
    // const vec3 n = vec3(-0.5, -c, s);
    const vec2 gr = cos(3.14159/vec2(3,5)); // a golden rectangle !
    const vec3 n = vec3(-gr, sqrt(1.-dot(gr,gr))); 
    p = abs(p);
    for (int i=0;i<3;i++) {
        float side = dot(p, n);
        if ( side > 0.0 ) break;
        p -= 2.*min(0., side)*n;
        if (i!=2) p.xy = abs(p.xy);
    }
    return p;
}    

// some rounded Ico & Dode

float Ico(vec3 p) {
    vec3 q = vec3(p.x - X_TO_ICO_VERTEX,-p.y,p.z-1.0); // position origin at the vertex
    q.zy *= Rot(ICODIHEDRAL*.5); 
    // min added for interior distance
    return length(max(q, 0.))+min(q.z, 0.);  // z can be used for interior distance
}

float Dode(vec3 p) {
    vec3 q = vec3(-p.x,p.y - Y_TO_DODE_VERTEX,p.z-1.0); // position origin at the vertex
    q.zx *= Rot(DODEDIHEDRAL*.5); 
    return length(max(q, 0.))+min(q.z, 0.); 
}

// I played with these functions

float GetDistDodecahedron(vec3 p) {
    vec3 q = p - ICOMIDEDGE;      // move
    q.xz *= Rot(DODEDIHEDRAL*.5); // rotate
    // rounded edge
    vec3 vtx = vec3(-q.x,q.y - Y_TO_DODE_VERTEX,q.z);
    // onioning and rounding
    float dDode = abs(length(max(vtx, 0.))+min(vtx.z, 0.)-.025)-.05; 
    // Holes are centered on the dodecaheron's faces center
    vec2 pCenter = vec2(q.x - X_TO_DODE_CENTER,q.y);
    float dHole = length( pCenter ) - .3;    
    // Smaller circles are centered somewhere between the middle of the face and the vertex of the Ico
    float dSmallHole = abs(abs(length( q.xy-mix(vec2(0.0,Y_TO_DODE_VERTEX),vec2(X_TO_DODE_CENTER,0.0),.3) ) - .07)-.030)-.015;
    // Spheres on the vertices (dodecahedron's vectrices are icosahedron face's centers)
    float dCorners = length(p - ICOMIDFACE * 1.24)-.12;    
    // blobby cross picked from IQ's magic box
    float dBlobbyCross = sdBlobbyCross(vec2(q.x-X_TO_DODE_CENTER*.2,q.y)*13.0,0.80)/13.0-.03;
    // combine
    float dist = dDode;
    float dCarvings = min(dHole,min(dSmallHole,dBlobbyCross));
    dist = smax(dist,-(dHole+.1),.04);
    dist += 0.008*smoothstep(0.01,-0.01,dCarvings);
    dist = smin(dist,dCorners,.07);
    return dist;
}

float GetDistIcosahedron(vec3 p) {
    vec3 q = p - ICOMIDEDGE;     // move
    q.yz *= Rot(ICODIHEDRAL*.5); // rotates the coordinates to have XY plan aligned with a ICO face's plan
    // rounded edge
    vec3 vtx = vec3(q.x - X_TO_ICO_VERTEX,-q.y,q.z);
    float dIco = length(max(vtx, 0.))+min(vtx.z, 0.)-.10;
    // Circles are centered on the icosahedron's faces
    float dBigHole = abs(abs(abs(length(q.xy - vec2(0.0,Y_TO_ICO_CENTER))-.17)-.08)-.04)-.02;
    // Smaller circles are centered somewhere between the middle of the face and the vertex of the Ico
    float dSmallHole = abs(abs(length( q.xy - mix(vec2(0.0,Y_TO_ICO_CENTER),vec2(X_TO_ICO_VERTEX,0.0),.60) ) - .07)-.025)-.010;
    // little chains of spheres on the edges
    float dBalls = length(q-vec3(round(q.x*20.0)/20.0,0.0,0.1))-.03;
    // Corners of the Ico
    q = p - ICOVERTEX * 1.3;      // move
    q.xz *= Rot(DODEDIHEDRAL*.5); // rotate
    float dCorners = length(q)-.04*(1.0+.5*sin(q.z*50.0));    
    // combine
    float dist = dIco;
    float dCarvings = min(dBigHole,dSmallHole);
    dist += 0.008*smoothstep(0.01,-0.01,dCarvings);
    dist = smin(dist,dCorners-.13,.1);
    dist = min(dist,dBalls);
    return dist;
}

// Not sure it is but looks like
float GetDistSmallStellatedDodecahedron(vec3 p) {
    vec3 q = p;
    q -= ICOMIDEDGE;
    float an = DODEDIHEDRAL*.5; // angle of a face with the rhombic face
    q.zx *= Rot(an);
    vec2 vtx = q.xy;
    float h = cos(DODEDIHEDRAL*.5)*X_TO_ICO_VERTEX; 
    h /= cos(an+DODEDIHEDRAL*.5); // Need to calculate again the intersection point with the folding plan
    vtx.x -= h;
    vec2 edge = normalize(vec2(h,-Y_TO_DODE_VERTEX));
    mat2 r = mat2(edge.x,edge.y,-edge.y,edge.x);
    vtx.xy *= r; // align xy coordinates to the edge
    float dStella = length(max(vec3(vtx,q.z), 0.)) + min(max(vtx.x,max(vtx.y,q.z)),0.);  // z can be used for interior distance
    float lines = clamp(q.x-h*.55,0.0,0.48);
    dStella -= 0.01*smoothstep(-0.3,0.9,sin(lines*3.14*20.));
    float dHorseShoe = sdHorseshoe(q.yx-vec2(0.0,0.4),vec2(sin(0.45),cos(0.45)),.14,vec2(.04));
    dStella -= .1; // rounding
    dStella = smax(dStella,-dHorseShoe,.02);
    // get a smooth non-convex dihedral angle is a challenge
    // here I build a base using 2 intersecting planes and smoothed angle
    float dBase = smax(p.z-1.13,dot(p,ICOMIDFACE)-1.19,0.005);
    return smin(dStella,dBase,.01 );
}

// Not sure it is but looks like
float GreatDodecahedron(vec3 p) {
    vec3 q = p;
    q -= ICOMIDEDGE;
    float an = -ICODIHEDRAL;
    q.zy *= Rot(an);
    vec3 vtx = vec3(q.x - X_TO_ICO_VERTEX,-q.y,q.z);
    float dDode = length(max(vtx, 0.0)) + min(vtx.z, 0.0);
    float dist = dDode -.05 + 0.008*smoothstep(0.01,-0.01,sdRoundedX(q.xy-vec2(0,0.15),.1,.02));
    return dist;
}

// Not sure it is but looks like
float GreatStellatedDodecahedron(vec3 p) {
    vec3 q = p;
    q -= ICOMIDEDGE; 
    float an = PI*.5-DODEDIHEDRAL*.5; // angle of a face with the rhombic face
    q.zy *= Rot(an);
    // tip of the polyhedron, point of intersection with folding plan
    // TODO : Will make it more understandable using a 2D plan in desmos
    // https://www.desmos.com/calculator/abjapu0oqi
    float h = cos(ICODIHEDRAL*.5)*Y_TO_DODE_VERTEX/cos(an+ICODIHEDRAL*.5); 
    vec2 vtx = vec2(-q.x,q.y-h); // changing coordinates 
    vec2 edge = normalize(vec2(X_TO_ICO_VERTEX,h));
    vtx.xy *= orient(edge); // align x coordinate to the edge vector
    float dStella = length(max(vec3(vtx,q.z), 0.)) + min(q.z,0.);  // z can be used for interior distance
    float lines = clamp(q.y-h*.45,0.0,0.48);
    dStella -= 0.01*smoothstep(-0.3,0.9,sin(lines*3.14*20.));
    // get a smooth non-convex dihedral angle is a challenge
    // here I build a base using smoothed intersecting planes
    float dBase = smax(p.z-1.25,dot(p,ICOVERTEX)-1.35,0.04);
    float dist = smin(dStella- .1,dBase,0.02);
    return dist;
}

// An experiment using some torus crossing at the intersect of the folding plans
float TorusFlower(vec3 q) {
    float r2 = .025;
    float d = 1e10;
    
    {
        float an = PI/3.;   // here you can change the width of the Vesicas
        float r = 1.0;
        vec3 n = vec3(1.,0.,0.);
        n.zx *= Rot(an);   // XZ symetry plane, rotated of an angle around the Y axis
        float dO = dot(ICOMIDFACE,n),         // calculate the distance between the plan and point ICOMIDFACE on the sphere
        rCircle = sqrt(1.-dO*dO);             // radius of the circle at intersection of plan and sphere
        d = distTorus(q-dO*n*r,rCircle*r,r2,n);   // draws the torus based this calculation
    }
    {
        float an = (PI/5.+PI/2.)/2.;   // I found impossible to have a value to make it tangent to both triangle edges
        float r = 0.95;
        vec3 n = erot(P35,normalize(ICOVERTEX-ICOMIDFACE),an); // P35 symetry plan, rotated of an angle around the hypotenuse axis
        float dO = dot(ICOMIDFACE,n),
        rCircle = sqrt(1.-dO*dO);
        d = min(d,distTorus(q-dO*n*r,rCircle*r,r2,n));
    }
    {
        float an = PI/5.;  
        float r = 1.05;
        vec3 n = vec3(0.,1.,0.);
        n.zy *= Rot(an);  
        float dO = dot(ICOVERTEX,n),         
        rCircle = sqrt(1.-dO*dO);            
        d = min(d,distTorus(q-dO*n*r,rCircle*r,r2,n));   
    }
    return d;
}

float sdCone( vec3 p, vec2 c )
{
    // c is the sin/cos of the angle
    vec2 q = vec2( length(p.xz), -p.y );
    float d = length(q-c*max(dot(q,c), 0.0));
    return d * ((q.x*c.y-q.y*c.x<0.0)?-1.0:1.0);
}

// https://www.highlandwoodworking.com/sphereturning.html
// Work in progress
float ChineseBall(vec3 p) {
    vec3 q = p;
    float dDode = length(p)-1.0;
    dDode = abs(dDode-.025)-.05; // onioning and rounding
    // Holes are centered on the dodecaheron's faces center
    q.xz *= Rot(DODEDIHEDRAL*.5); // rotates the coordinates to have XY plan aligned with a DODE face plan
    vec2 pCenter = vec2(q.x - X_TO_DODE_CENTER,q.y);
    pCenter = q.xy;
    float dHole = length( pCenter ) - .55;    
    // shaking mixing the distances
    float dist = dDode;
    dist = smax(dist,-(dHole+.1),.04);
    return dist;
}

// IQ & filbs111
float sdOctahedron(vec3 p, float s)
{
    p = abs(p);
    float m = p.x + p.y + p.z - s;
    vec3 r = 3.0*p - m;
    vec3 o = min(r, 0.0);
    o = max(r*2.0 - o*3.0 + (o.x+o.y+o.z), 0.0);
    return length(p - s*o/(o.x+o.y+o.z));
}
// flockaroo - https://www.shadertoy.com/view/dlcGRH
float GetDistFoldedOctahedron(vec3 p) {
    float dist = sdOctahedron(p,1.5)-.04;
    return dist;
}



const float nShapes = 8.;
float shapeID = 0.0;
float GetDist(vec3 p) {
    vec3 q = opIcosahedralSymmetry(p);
//     Change shape ID here
// shapeID=6.5;
    float d = 1e10;
    if ( shapeID < 0.5 )
        d = GetDistDodecahedron(q);
    else if ( shapeID < 1.5 )
        d = GetDistIcosahedron(q);
    else if ( shapeID < 2.5 )
        { d = GetDistSmallStellatedDodecahedron(q/0.8)*0.8; }
    else if ( shapeID < 3.5 )
        { d = GreatDodecahedron(q/1.2)*1.2; }
    else if ( shapeID < 4.5 )
        { d = GreatStellatedDodecahedron(q*1.7)/1.7; }
    else if ( shapeID < 5.5 )
        { d = TorusFlower(q/1.22)*1.22; } 
    else if ( shapeID < 6.5 )
        { d = ChineseBall(q); }
    else if ( shapeID < 7.5 )
        { d = GetDistFoldedOctahedron(q); }
     float d2=min(q.x,min(q.y,dot(q,P35)))-.01;
     d2 = max(d2,q.z-1.);
   //  d = min(d,d2); // show folded space

    return d;
    
}

float RayMarch(vec3 ro, vec3 rd) {
	float dO=0.;
    for(int i=0; i<MAX_STEPS; i++) {
    	vec3 p = ro + rd*dO;
        float dS = GetDist(p);
        dO += dS;
        if(dO>MAX_DIST || abs(dS)<SURF_DIST) break;
    }
    return dO;
}

vec3 GetNormal(vec3 p) {
	float d = GetDist(p);
    vec2 e = vec2(.001, 0);
    vec3 n = d - vec3(
        GetDist(p-e.xyy),
        GetDist(p-e.yxy),
        GetDist(p-e.yyx));
    return normalize(n);
}

vec3 GetRayDir(vec2 uv, vec3 p, vec3 l, float z) {
    vec3 f = normalize(l-p),
        r = normalize(cross(vec3(0,1,0), f)),
        u = cross(f,r),
        c = f*z,
        i = c + uv.x*r + uv.y*u,
        d = normalize(i);
    return d;
}

float calcSoftshadow( in vec3 ro, in vec3 rd, in float mint, in float tmax )
{
    float res = 1.0;
    float t = mint;
    for( int i=0; i<24; i++ )
    {
		float h = GetDist( ro + rd*t );
        float s = clamp(8.0*h/t,0.0,1.0);
        res = min( res, s*s*(3.0-2.0*s) );
        t += clamp( h, 0.02, 0.2 );
        if( res<0.004 || t>tmax ) break;
    }
    return clamp( res, 0.0, 1.0 );
}

float calcOcclusion( in vec3 pos, in vec3 nor )
{
	float occ = 0.0;
    float sca = 1.0;
    for( int i=0; i<5; i++ )
    {
        float h = 0.01 + 0.33*float(i)/4.0;
        vec3 opos = pos + h*nor;
        float d = GetDist( opos );
        occ += (h-d)*sca;
        sca *= 0.95;
    }
    return clamp( 1.0 - 2.0*occ, 0.0, 1.0 );
}


void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    vec3 orange = vec3(1.00,.25,0.01);
    vec3 sun   = vec3(1.64,1.27,0.99);
    vec2 uv = (fragCoord-.5*iResolution.xy)/iResolution.y;
	vec2 m = (2.0*iMouse.xy-iResolution.xy)/iResolution.y;
    vec3 ro = vec3(0, 0, -2.8);
    shapeID = floor(fract(T/nShapes)*nShapes);
    if( iMouse.z>0.001 )
    {
        ro.yz *= Rot(-m.y*3.14);
        ro.xz *= Rot(-m.x*6.2831);
    } else {   
        ro.zx *= Rot(T*4.0);
        ro.xy *= Rot(T*2.);
    }
    vec3 rd = GetRayDir(uv, ro, vec3(0,0.,0), 1.0);
    vec3 bg = orange*cos(length(uv));
    vec3 col = bg;
   
    float d = RayMarch(ro, rd);

    if(d<MAX_DIST) {
        vec3 p = ro + rd * d;
        vec3 nor = texBump(iChannel0,p*.5,GetNormal(p),.005);
        float occ = max(.1,calcOcclusion(p,nor));
        vec3  lig1 = normalize( vec3( 0.10, 1.50, 0.40) );
        vec3  lig2 = normalize( vec3(-1.50,-1.00, -1.00) );
        vec3  lig3 = normalize( vec3( 1.50,-1.00, -1.00) );
        // IQ's Blinn-Phong specular formula
        float lig1_spe = pow(clamp(dot(nor,normalize( lig1-rd )),0.0,1.0),8.0) * max(0.0,dot(nor,lig1));
        float lig2_spe = pow(clamp(dot(nor,normalize( lig2-rd )),0.0,1.0),8.0) * max(0.0,dot(nor,lig2));
        float lig3_spe = pow(clamp(dot(nor,normalize( lig3-rd )),0.0,1.0),8.0) * max(0.0,dot(nor,lig3));
        float sha1 = calcSoftshadow( p+0.01*nor, lig1, 0.01, 2.1 );
        col = vec3(0);
        col += 0.6 * lig1_spe * sun * sha1;
        col += 0.2 * lig2_spe * orange * occ;
        col += 0.2 * lig3_spe * orange * occ;        
    } 
    
    // https://graphtoy.com/?f1(x,t)=floor(fract(x/10)*10)&v1=true&f2(x,t)=pow(.5+.5*cos(x*6.28),32)&v2=true&f3(x,t)=&v3=false&f4(x,t)=&v4=false&f5(x,t)=&v5=false&f6(x,t)=&v6=false&grid=1&coords=1.645933014354067,2.5645933014354068,12
    col = mix(col,bg,pow(.5+.5*cos((2.*PI*fract(T))),32.));
    col = pow(col, vec3(.4545));	// gamma correction
    
    fragColor = vec4(col,1.0);
}
