// Common (common) — Super Shader GUI 98 by P_Malin
// https://www.shadertoy.com/view/Xs2cR1

const int
    DATA_UICONTEXT						= 0,	
	DATA_CHECKBOX_SHOW_IMAGE 			= 1,
	DATA_WINDOW_CONTROLS   				= 2,
	DATA_BACKGROUND_IMAGE				= 3,
	DATA_BACKGROUND_BRIGHTNESS			= 4,
	DATA_BACKGROUND_SCALE        		= 5,
	DATA_WINDOW_IMAGE_CONTROL			= 6,
	DATA_IMAGE_BRIGHTNESS 				= 7,
	DATA_WINDOW_IMAGEA					= 8,
	DATA_WINDOW_IMAGEB					= 9,
    DATA_BUTTONA						= 10,
    DATA_BG_COLOR						= 11,
    DATA_IMAGE_COLOR					= 12,
    DATA_WINDOW_EDIT_COLOR				= 13,
    DATA_EDIT_WHICH_COLOR				= 14,
    DATA_SCROLLBAR_PANEL				= 15;
    
const int
    IDC_CHECKBOX_SHOW_IMAGE 			= 0,
	IDC_WINDOW_CONTROLS      			= 1,
	IDC_CHECKBOX_BACKGROUND_IMAGE 		= 2,
	IDC_SLIDER_BACKGROUND_BRIGHTNESS	= 3,
	IDC_SLIDER_BACKGROUND_SCALE        	= 4,
	IDC_WINDOW_IMAGE_CONTROL			= 5,
	IDC_SLIDER_IMAGE_BRIGHTNESS			= 6,
	IDC_WINDOW_IMAGEA   				= 7,
	IDC_WINDOW_IMAGEB   				= 8,
    IDC_BUTTONA							= 9,
    IDC_BUTTONB							= 10,
    IDC_WINDOW_EDIT_COLOR       		= 11,
    IDC_COLOR_PICKER 					= 12,
    IDC_SCROLLBAR_PANEL					= 13;

