// Image (image) — Tileable Perlin-Worley 3D by piyushslayer
// https://www.shadertoy.com/view/3dVXDc

/**
An implementation of tileable 3D Perlin-Worley noise for modeling volumetric clouds
inspired from the chapter Real-Time Volumetric Cloudscapes by Andrew Schneider
(Guerrilla Games). The first column is the perlin-worley noise generated by remapping
perlin noise with the lowest frequency worley fbm. The next 3 columns are worley fbms
with increasing frequencies, and are used to model the cloud shapes which are rendered
in the last column. See the common tab for all the noise functions used.
*/

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    vec2 st = fragCoord / iResolution.xy;
    vec2 uv = fragCoord / iResolution.y;
    st.x *= 5.; // 5 columns for different noises
    uv -= .02 * iTime;

    vec3 col = vec3(0.);
    
    float perlinWorley = textureLod(iChannel0, uv * .5, 0.).x;
    
    // worley fbms with different frequencies
    vec3 worley = textureLod(iChannel0, uv, 0.).yzw;
    float wfbm = worley.x * .625 +
        		 worley.y * .125 +
        		 worley.z * .25; 
    
    // cloud shape modeled after the GPU Pro 7 chapter
    float cloud = remap(perlinWorley, wfbm - 1., 1., 0., 1.);
    cloud = remap(cloud, .85, 1., 0., 1.); // fake cloud coverage
    
    if (st.x < 1.)
        col += perlinWorley;
    else if(st.x < 2.)
        col += worley.x;
    else if(st.x < 3.)
        col += worley.y;
	else if(st.x < 4.)
        col += worley.z;
    else if(st.x < 5.)
        col += cloud;
            
    // column dividers
    float div = smoothstep(.01, 0., abs(st.x - 1.));
    div += smoothstep(.01, 0., abs(st.x - 2.));
	div += smoothstep(.01, 0., abs(st.x - 3.));
    div += smoothstep(.01, 0., abs(st.x - 4.));
        
    col = mix(col, vec3(0., 0., .866), div);
        
    fragColor = vec4(col,1.0);
}