// Buffer A (buffer) — Tons of Spatial-Sorted Particles by cornusammonis
// https://www.shadertoy.com/view/XsjyRm

#define T(d) texelFetch(iChannel0, d, 0).xy

#define FULL 5 // sorting window size (e.g. 5x5)
#define STRIDE 25 // stride length
#define SORT_WINDOW (FULL*STRIDE)
#define DIM (FULL*FULL)

//#define TARGET_EDGE // if defined, use the corners of the buffers (e.g. UVs (0,0) or (1,1)) as sort targets
#define REVERSE_ORDER // if defined we sort from inner-to-outer, and if undefined we sort from outer-to-inner

// reordering targets reduces artifacts related to the choice 
// of which quadrant of the sorting window we sort first.
#define REORDER_TARGETS
#ifdef REORDER_TARGETS
	#define REORDER(k) ((iFrame+3+k)%4)
#else
	#define REORDER(k) k
#endif

#define R(v) (vec2(v) / iResolution.xy)

// Hash from Dave Hoskin's "Hash without Sine": https://www.shadertoy.com/view/4djSRW
#define MOD3 vec3(.1031,.11369,.13787)

vec3 hash33(vec3 p3)
{
	p3 = fract(p3 * MOD3);
    p3 += dot(p3, p3.yxz+19.19);
    return -1.0 + 2.0 * fract(vec3((p3.x + p3.y)*p3.z, (p3.x+p3.z)*p3.y, (p3.y+p3.z)*p3.x));
}

// Simplex Noise from candycat's "Noise Lab (3D)": https://www.shadertoy.com/view/4sc3z2
float simplex_noise(vec3 p)
{
    p *= 4.0;
    const float K1 = 0.333333333;
    const float K2 = 0.166666667;
    
    vec3 i = floor(p + (p.x + p.y + p.z) * K1);
    vec3 d0 = p - (i - (i.x + i.y + i.z) * K2);
    
    // thx nikita: https://www.shadertoy.com/view/XsX3zB
    vec3 e = step(vec3(0.0), d0 - d0.yzx);
	vec3 i1 = e * (1.0 - e.zxy);
	vec3 i2 = 1.0 - e.zxy * (1.0 - e);
    
    vec3 d1 = d0 - (i1 - 1.0 * K2);
    vec3 d2 = d0 - (i2 - 2.0 * K2);
    vec3 d3 = d0 - (1.0 - 3.0 * K2);
    
    vec4 h = max(0.6 - vec4(dot(d0, d0), dot(d1, d1), dot(d2, d2), dot(d3, d3)), 0.0);
    vec4 n = h * h * h * h * vec4(dot(d0, hash33(i)), dot(d1, hash33(i + i1)), dot(d2, hash33(i + i2)), dot(d3, hash33(i + 1.0)));
    
    return dot(vec4(31.316), n);
}


#define TIME iTime / 10.0

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    ivec2 iFC  = ivec2(fragCoord);
    ivec2 iuv = iFC;
    vec2 tx = 1.0 / iResolution.xy;
    vec2 pos = T(iuv);
    vec2 new_pos = pos;
    
    ivec2 iRes = ivec2(iResolution.xy);
    
    // PRNG for sort offset
    vec3 hash = hash33(iTime * vec3(-5.17, 14.94, -7.56));
    ivec2 offs = ivec2(float(SORT_WINDOW) * hash.xy);
    //ivec2 offs = (SORT_WINDOW/2)*ivec2((iFrame % 3-1), ((iFrame+1)% 3-1));

    ivec2 uvm = iuv + offs;
    ivec2 shift = (STRIDE + (uvm % STRIDE)) % STRIDE;
    ivec2 subp = ((SORT_WINDOW + ((uvm - shift) % SORT_WINDOW)) % SORT_WINDOW) / STRIDE;
    ivec2 subp_stride = STRIDE * subp;
    ivec2 base_uv = iuv - subp_stride;
    
    /* This is the default sorting order generated by the algorithm below for a 5x5 window:
         0  4  8  12  1
        15 16 20  17  5
        11 23 24  21  9
         7 19 22  18 13
         3 14 10  6   2
	*/
 
    if (all(greaterThanEqual(base_uv,ivec2(0))) && all(lessThanEqual(base_uv + STRIDE * FULL, iRes))) {
        bool del[DIM];
        vec2 sort[DIM];
        vec2 posv[DIM];
        ivec2 order[DIM];
        
        for (int i = 0; i < DIM; i++) {
            del[i] = false;
            sort[i] = vec2(0);
            posv[i] = vec2(0);
        }
        
        int MAX = DIM/4;

        if (FULL % 2 == 1) {
            order[DIM-1] = ivec2(FULL/2);
            MAX = (DIM - 1)/4;
        }

        int ic = 0;
        int m  = 0;
        int id = FULL - 1;

        for (int i = 0; i < MAX; i++) {
            if (ic == id) {
                id = id - 2;
                ic = 0;
                m++;
            }
            order[4*i+REORDER(0)] = ivec2(ic+m,    id+m);
            order[4*i+REORDER(1)] = ivec2(id+m,    id-ic+m);
            order[4*i+REORDER(2)] = ivec2(id-ic+m, m);
            order[4*i+REORDER(3)] = ivec2(m,       ic+m);

            ic++;
        }

        for (int i = 0; i < FULL; i++) {
            for (int j = 0; j < FULL; j++) {
                posv[i + j * FULL] = T(base_uv + STRIDE*ivec2(i,j));
            }
        }

        #ifdef REVERSE_ORDER
        for (int i = DIM - 1; i >= 0; i--) {
        #else
        for (int i = 0; i < DIM; i++) {
        #endif
            vec2 closest = vec2(1e6);
            float closest_distance = 1e6;
            int closest_index = -1;

            #ifdef TARGET_EDGE
                vec2 tgt = vec2(order[i]) / float(FULL-1);
            #else
            	vec2 tgt = R(base_uv + STRIDE*order[i]);
            #endif

            int tgt_index = order[i].x + order[i].y * FULL;
            for (int j = 0; j < DIM; j++) { 
                float dist  = distance(posv[j],tgt);
                if (dist <= closest_distance && !del[j]) {
                    closest_index = j; 
                    closest = posv[j];
                    closest_distance = dist;
                }
            }
            del[closest_index] = true;
            sort[tgt_index] = closest;
        }

        new_pos = sort[subp.x + subp.y * FULL];
    }

    vec2 uv = fragCoord.xy / iResolution.xy;
    vec2 aspect = vec2(1, iResolution.y / iResolution.x);
    float delta = 1.0*tx.x;
    float noise  = simplex_noise(vec3(aspect * pos, TIME));
    float noiseY = simplex_noise(vec3(aspect * pos + vec2(0, delta), TIME));
    float noiseX = simplex_noise(vec3(aspect * pos + vec2(delta, 0), TIME));
    
    vec2 noiseV = vec2(noiseX, noiseY) - vec2(noise);

    if (iFrame < 2) {
        fragColor = 0.5 + vec4(vec2(uv.xy - 0.5).yx * vec2(1,-1),vec2(0));
    } else {
        vec2 curl = 0.5 * normalize(vec2(noiseV.y,-noiseV.x));
    	fragColor = vec4(mod(new_pos + curl * tx.xx,vec2(1)), vec2(0));    
    }   

}

