// Buffer A (buffer) — Iridescent Car Paint by piyushslayer
// https://www.shadertoy.com/view/mdSyWd

/**
    A quasi-realistic looking carbon fiber texture pattern based on overlapping two different sets of uv maps
    mixed using a zigzag checkered pattern. The checkered pattern is stored in x channel of the carbon fiber
    map. The anisotropic brushed "metal" look is generated by stretching two sets of perlin fbm noise along the
    x and y axis and then mixing them using the same zigzag checkered pattern. A second map is also generated
    that stores the heightmap for each "weave" in the mesh. Finally everything is mixed together using these 
    two masks with 2 distinct colors to differentiate between the horizontal and vertical weaves. Some fake lighting
    is also added to enhance the effect of the heightmap & the anisotropic brushes on each weave of the mesh. Try playing
    around with different settings below to customize the look of the texture. 
*/

#define WEAVE_SCALE 80.0
#define HORIZONTAL_WEAVE_COLOR vec3(0.003)
#define VERTICAL_WEAVE_COLOR   vec3(0.01)

#define ANISOTROPIC_MASK 1
#define ANISOTROPIC_ANIMATION 0
#define ANISOTROPIC_THRESHOLD 0.3
#define ANISOTROPIC_ANIMATION_SPEED 0.02

#define DIFFUSE_SCALE 2.0
#define SPECULAR_SCALE 0.5

float PerlinNoise(vec2 x, float freq) 
{
    x *= freq; // tile
    
    vec2 f = fract(x);
    x = floor(x);

	float a = Hash12(uvec2(abs(mod(x, freq))));
    float b = Hash12(uvec2(abs(mod(x + vec2(1.0, 0.0), freq))));
    float c = Hash12(uvec2(abs(mod(x + vec2(0.0, 1.0), freq))));
    float d = Hash12(uvec2(abs(mod(x + vec2(1.0, 1.0), freq))));

    vec2 u = f * f * (3.0 - 2.0 * f);
	return mix(a, b, u.x) + (c - a) * u.y * (1.0 - u.x) + (d - b) * u.x * u.y;
}



float PerlinFbm (vec2 uv, float freq, int octaves)
{
    float amp = .5;
    float noise = 0.;
    
    for (int i = 0; i < octaves; ++i)
    {
        noise += amp * PerlinNoise(uv, freq);
        amp *= .5;
        freq *= 2.;
    }
    return noise;
}

vec2 GenerateCarbonFiberMap(in vec2 uv)
{
    vec2 gridUv = uv * WEAVE_SCALE;// * vec2(1.0, iResolution.y / iResolution.x); // Scale grid row size based on aspect ratio.
    vec2 gridId = floor(gridUv);
    float maskScaleInverse = 0.5;
    vec2 maskOffset = (gridUv + gridId.yx) * maskScaleInverse;
    
    float patternMask = mod(floor(maskOffset.x), 2.0); // zigzag pattern
    vec2 gradients = 1.0 - abs(fract(maskOffset) - 0.5); // horizontal and vertical gradient patterns
    gradients -= 0.5;
    gradients = Saturate(pow(gradients, vec2(0.25)));
    float heightMap = mix(gradients.y, gradients.x, patternMask); // mix both gradients based on the zigzag pattern
    
#if ANISOTROPIC_MASK
    float anisotropicBrush = mix(PerlinFbm(uv * vec2(50.0, 0.1) + vec2(0.0, uv.x * 8.0) 
#if ANISOTROPIC_ANIMATION
                                           + iTime * ANISOTROPIC_ANIMATION_SPEED
#endif
                                           , 32.0, 8), // vertical anisotropic
                                 PerlinFbm(uv * vec2(0.1, 50.0) + vec2(uv.y * 8.0, 0.0)
#if ANISOTROPIC_ANIMATION
                                           + iTime * ANISOTROPIC_ANIMATION_SPEED
#endif
                                           , 32.0, 8), // horizontal anisotropic
                                 patternMask);
    heightMap = mix(heightMap, anisotropicBrush, ANISOTROPIC_THRESHOLD);
#endif
    return vec2(patternMask, heightMap * heightMap);

}

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{  
    fragColor = texelFetch(iChannel0, ivec2(fragCoord), 0);
    float lastFrameWidth = texelFetch(iChannel1, ivec2(2, 0), 0).x;
    
    if (iFrame == 0 || floor(lastFrameWidth) != iResolution.x)
    {
        vec2 uv = fragCoord / iResolution.xy;
        vec2 carbonFiber = GenerateCarbonFiberMap(uv);
        vec3 outColor = vec3(1.0);
        outColor *= carbonFiber.y * mix(VERTICAL_WEAVE_COLOR, HORIZONTAL_WEAVE_COLOR, carbonFiber.x);
        fragColor = vec4(outColor, carbonFiber.y);
    }    
}